services:

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./certs:/certs
    depends_on:
      - signaling

  signaling:
    build: ./server
    network_mode: "host" 
    # ports:
    #   - "3000:3000"
    #   - "40000-49999:40000-49999/udp" 
    volumes:
      - ./certs:/certs
    environment:
      - ANNOUNCED_IP=192.168.29.230

  coturn:
    image: coturn/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    command: >
      -n
      --log-file=stdout
      --min-port=49152
      --max-port=49200
      --realm=webrtc.local
      --user=test:test
      --no-cli
      --no-multicast-peers
      --fingerprint