version: "3.8"

services:

  client:
    build: ./client
    container_name: pipesam-client
    ports:
      - "5173:5173"
    depends_on:
      - signaling

  signaling:
    build: ./server
    container_name: pipesam-server
    ports:
      - "3000:3000"

  coturn:
    image: coturn/coturn
    container_name: pipesam-turn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    command: >
      -n
      --log-file=stdout
      --min-port=49152
      --max-port=49200
      --realm=webrtc.local
      --user=test:test
      --no-cli
      --no-multicast-peers
      --fingerprint

